config/routes.rb
Rails.application.routes.draw do

  resources :iga_baselines
  root 'iga_baselines#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iga_baseline.rb
class IgaBaseline < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/iga_baselines_controller.rb
class IgaBaselinesController < ApplicationController
  before_action :set_iga_baseline, only: [:show, :edit, :update, :destroy]

  # GET /iga_baselines
  # GET /iga_baselines.json
  def index
    @iga_baselines = IgaBaseline.all
  end

  # GET /iga_baselines/1
  # GET /iga_baselines/1.json
  def show
  end

  # GET /iga_baselines/new
  def new
    @iga_baseline = IgaBaseline.new
  end

  # GET /iga_baselines/1/edit
  def edit
  end

  # POST /iga_baselines
  # POST /iga_baselines.json
  def create
    @iga_baseline = IgaBaseline.new(iga_baseline_params)

    respond_to do |format|
      if @iga_baseline.save
        format.html { redirect_to @iga_baseline, notice: 'Iga baseline was successfully created.' }
        format.json { render :show, status: :created, location: @iga_baseline }
      else
        format.html { render :new }
        format.json { render json: @iga_baseline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iga_baselines/1
  # PATCH/PUT /iga_baselines/1.json
  def update
    respond_to do |format|
      if @iga_baseline.update(iga_baseline_params)
        format.html { redirect_to @iga_baseline, notice: 'Iga baseline was successfully updated.' }
        format.json { render :show, status: :ok, location: @iga_baseline }
      else
        format.html { render :edit }
        format.json { render json: @iga_baseline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iga_baselines/1
  # DELETE /iga_baselines/1.json
  def destroy
    @iga_baseline.destroy
    respond_to do |format|
      format.html { redirect_to iga_baselines_url, notice: 'Iga baseline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iga_baseline
      @iga_baseline = IgaBaseline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iga_baseline_params
      params.require(:iga_baseline).permit(:server_name, :ip, :os, :version_os, :qmgr, :version_mq, :broker, :version_broker, :comment)
    end
end

app/controllers/say_controller.rb
require 'json'

# Controller and action definition for uri say/hello
# See routing configuration in config/routes.rb
class SayController < ApplicationController
  def hello
    # get user ip from request
    @yourip = request.remote_ip
    
    # use params[:name] to get request parameter value by name
    # @parameter = params[:name]
    
    # get Ruby version and Rails version
    @ruby_version = RUBY_VERSION
    @rails_version = Rails::VERSION::STRING
    
    # environment variable 'VCAP_SERVICES' is in JSON format. You may use JSON.parse() to get Ruby hash
    # 'VCAP_SERVICES' is empty if your didn't bind any service to the application
    # @vcap_services = ENV['VCAP_SERVICES']
    # @home = ENV['HOME']
    # @memory_limit = ENV['MEMORY_LIMIT']
    # @port = ENV['PORT']
    # @pwd = ENV['PWD']
    # @tmpdir = ENV['TMPDIR']
    # @user = ENV['USER']
    # 'VCAP_APPLICATION' is in JSON format, use JSON.parse() to get Ruby hash
    # @vcap_app = JSON.parse(ENV['VCAP_APPLICATION'])
    
    # Variables Defined by Ruby Buildpack
    # @bundle_bin_path = ENV['BUNDLE_BIN_PATH']
    # @bundle_gemfile = ENV['BUNDLE_GEMFILE']
    # @bundle_without = ENV['BUNDLE_WITHOUT']
    # @database_url = ENV['DATABASE_URL']
    # @gem_home = ENV['GEM_HOME']
    # @rack_env = ENV['RACK_ENV']
    # @rails_env = ENV['RAILS_ENV']
    
    env = {}
    # loop to parse all JSON object
    # @env is available in the view: views/say/hello.html.erb
    ENV.each do |key, value|
        begin
            obj = JSON.parse(value)
            env[key] = JSON.pretty_generate(obj)
        rescue
            env[key] = value
        end
      end
    @env = env
    
  end
end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/iga_baselines_helper.rb
module IgaBaselinesHelper
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/views/iga_baselines/_form.html.erb
<%= form_for(iga_baseline) do |f| %>
  <% if iga_baseline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(iga_baseline.errors.count, "error") %> prohibited this iga_baseline from being saved:</h2>

      <ul>
      <% iga_baseline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server_name %>
    <%= f.text_field :server_name %>
  </div>

  <div class="field">
    <%= f.label :ip %>
    <%= f.text_field :ip %>
  </div>

  <div class="field">
    <%= f.label :os %>
    <%= f.text_field :os %>
  </div>

  <div class="field">
    <%= f.label :version_os %>
    <%= f.text_field :version_os %>
  </div>

  <div class="field">
    <%= f.label :qmgr %>
    <%= f.text_field :qmgr %>
  </div>

  <div class="field">
    <%= f.label :version_mq %>
    <%= f.text_field :version_mq %>
  </div>

  <div class="field">
    <%= f.label :broker %>
    <%= f.text_field :broker %>
  </div>

  <div class="field">
    <%= f.label :version_broker %>
    <%= f.text_field :version_broker %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iga_baselines/edit.html.erb
<h1>Editing Iga Baseline</h1>

<%= render 'form', iga_baseline: @iga_baseline %>

<%= link_to 'Show', @iga_baseline %> |
<%= link_to 'Back', iga_baselines_path %>

app/views/iga_baselines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Iga Baselines</h1>


<table>
  <thead>
    <tr>
      <th>Server name</th>
      <th>Ip</th>
      <th>Os</th>
      <th>Version os</th>
      <th>Qmgr</th>
      <th>Version mq</th>
      <th>Broker</th>
      <th>Version broker</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iga_baselines.each do |iga_baseline| %>
      <tr>
        <td><%= iga_baseline.server_name %></td>
        <td><%= iga_baseline.ip %></td>
        <td><%= iga_baseline.os %></td>
        <td><%= iga_baseline.version_os %></td>
        <td><%= iga_baseline.qmgr %></td>
        <td><%= iga_baseline.version_mq %></td>
        <td><%= iga_baseline.broker %></td>
        <td><%= iga_baseline.version_broker %></td>
        <td><%= iga_baseline.comment %></td>
        <td><%= link_to 'Show', iga_baseline %></td>
        <td><%= link_to 'Edit', edit_iga_baseline_path(iga_baseline) %></td>
        <td><%= link_to 'Destroy', iga_baseline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iga Baseline', new_iga_baseline_path %>

app/views/iga_baselines/new.html.erb
<h1>New Iga Baseline</h1>

<%= render 'form', iga_baseline: @iga_baseline %>

<%= link_to 'Back', iga_baselines_path %>

app/views/iga_baselines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server name:</strong>
  <%= @iga_baseline.server_name %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @iga_baseline.ip %>
</p>

<p>
  <strong>Os:</strong>
  <%= @iga_baseline.os %>
</p>

<p>
  <strong>Version os:</strong>
  <%= @iga_baseline.version_os %>
</p>

<p>
  <strong>Qmgr:</strong>
  <%= @iga_baseline.qmgr %>
</p>

<p>
  <strong>Version mq:</strong>
  <%= @iga_baseline.version_mq %>
</p>

<p>
  <strong>Broker:</strong>
  <%= @iga_baseline.broker %>
</p>

<p>
  <strong>Version broker:</strong>
  <%= @iga_baseline.version_broker %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @iga_baseline.comment %>
</p>

<%= link_to 'Edit', edit_iga_baseline_path(@iga_baseline) %> |
<%= link_to 'Back', iga_baselines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IGABaseline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>

app/views/say/hello.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<TITLE>Ruby on Rails Starter Application</TITLE>
		<link href='/stylesheets/style.css' rel='stylesheet'>
	</HEAD>
 
	<BODY>
		  <table>
			<tr>
			  <td style='width:30%;'>
				<img class = 'newappIcon' src='assets/newapp-icon.png'>
			  </td>
			  <td>
				<h1 id = "message">Hello World!</h1>
				<p class='description'></p> Thanks for creating a <span class="blue">Ruby on Rails Starter Application</span>.
			  </td>
			</tr>
		  </table>
	</BODY>
</HTML>

app/views/startup/index.html.erb
<h1>Startup#index</h1>
<p>Find me in app/views/startup/index.html.erb</p>